# Generated by Django 3.1.7 on 2021-03-12 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0003_base64'),
        ('veterinaria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exame',
            name='consulta',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='receituario',
            name='imagem',
        ),
        migrations.AddField(
            model_name='exame',
            name='animal',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='commons.animal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exame',
            name='anexo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commons.base64'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='anexo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anexo', to='commons.base64'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='bula',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bula', to='commons.base64'),
        ),
        migrations.AlterField(
            model_name='receituario',
            name='anexo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commons.base64'),
        ),
    ]
