# Generated by Django 3.1.7 on 2021-03-07 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('data', models.DateField(null=True)),
                ('observacao', models.TextField(null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('alterado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.CharField(max_length=250, null=True)),
                ('alterado_por', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cartao_Vacinacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=250)),
                ('observacao', models.TextField(null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('alterado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.CharField(max_length=250, null=True)),
                ('alterado_por', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=320)),
                ('numero', models.PositiveIntegerField(null=True)),
                ('complemento', models.CharField(max_length=320, null=True)),
                ('bairro', models.CharField(max_length=320, null=True)),
                ('municipio', models.CharField(max_length=320, null=True)),
                ('estado', models.CharField(max_length=320, null=True)),
                ('cep', models.CharField(max_length=320, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('alterado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.CharField(max_length=250, null=True)),
                ('alterado_por', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crmv', models.CharField(max_length=50, null=True, unique=True)),
                ('foto', models.ImageField(null=True, upload_to='')),
                ('nome', models.CharField(max_length=250)),
                ('sobrenome', models.CharField(max_length=250, null=True)),
                ('email', models.CharField(max_length=250, null=True)),
                ('telefone_1', models.CharField(max_length=250, null=True)),
                ('telefone_2', models.CharField(max_length=250, null=True)),
                ('usuario', models.CharField(max_length=250)),
                ('senha', models.CharField(max_length=250)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('alterado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.CharField(max_length=250, null=True)),
                ('alterado_por', models.CharField(max_length=250, null=True)),
                ('endereco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commons.endereco')),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='')),
                ('data', models.DateField(null=True)),
                ('legenda', models.CharField(max_length=250, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('alterado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.CharField(max_length=250, null=True)),
                ('alterado_por', models.CharField(max_length=250, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.album')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(null=True, upload_to='')),
                ('cpf', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=250)),
                ('sobrenome', models.CharField(max_length=250, null=True)),
                ('email', models.CharField(max_length=250, null=True)),
                ('telefone_1', models.CharField(max_length=250, null=True)),
                ('telefone_2', models.CharField(max_length=250, null=True)),
                ('inadimplente', models.BooleanField(default=False)),
                ('genero', models.CharField(max_length=250, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('alterado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.CharField(max_length=250, null=True)),
                ('alterado_por', models.CharField(max_length=250, null=True)),
                ('endereco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commons.endereco')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(null=True, upload_to='')),
                ('rga', models.CharField(max_length=250, unique=True)),
                ('nome', models.CharField(max_length=250)),
                ('especie', models.CharField(max_length=250, null=True)),
                ('raca', models.CharField(max_length=250, null=True)),
                ('cor', models.CharField(max_length=250, null=True)),
                ('nascimento', models.DateField(null=True)),
                ('peso', models.FloatField(null=True)),
                ('porte', models.CharField(max_length=250, null=True)),
                ('castrado', models.BooleanField(default=False)),
                ('sexo', models.CharField(max_length=250, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('alterado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.CharField(max_length=250, null=True)),
                ('alterado_por', models.CharField(max_length=250, null=True)),
                ('cartao_vacinacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commons.cartao_vacinacao')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.animal'),
        ),
    ]
