# Generated by Django 3.1.7 on 2021-03-09 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='tutor',
            new_name='cliente',
        ),
    ]
