# Generated by Django 3.1.7 on 2021-03-12 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0002_auto_20210308_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base64',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_base64', models.TextField()),
                ('extensao', models.CharField(max_length=250)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('alterado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.CharField(max_length=250, null=True)),
                ('alterado_por', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
