# Generated by Django 3.1.7 on 2021-03-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0003_base64'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='data_castracao',
            field=models.DateField(null=True),
        ),
    ]
