from django.urls.conf import include
from django.urls import path
from rest_framework_jwt.views import obtain_jwt_token, verify_jwt_token, refresh_jwt_token
from .repository import consulta_repository, medicamento_repository, vacina_repository, condicao_especial_repository, medicamento_administrado_repository, cirurgia_repository, emergencia_repository, atendimento_repository, doenca_repository, receituario_repository


urlpatterns = [
    path('consulta', consulta_repository.consultas_findall),
    path('consulta/<int:pk>', consulta_repository.consulta_get),
    path('consulta/<int:pk>/edit', consulta_repository.consulta_edit),
    path('consulta/create', consulta_repository.consulta_create),
    path('consulta/<int:pk>/delete', consulta_repository.consulta_delete),
    path('cirurgia', cirurgia_repository.cirurgias_findall),
    path('cirurgia/<int:pk>', cirurgia_repository.cirurgia_get),
    path('cirurgia/<int:pk>/edit', cirurgia_repository.cirurgia_edit),
    path('cirurgia/create', cirurgia_repository.cirurgia_create),
    path('cirurgia/<int:pk>/delete', cirurgia_repository.cirurgia_delete),
    path('emergencia', emergencia_repository.emergencias_findall),
    path('emergencia/<int:pk>', emergencia_repository.emergencia_get),
    path('emergencia/<int:pk>/edit', emergencia_repository.emergencia_edit),
    path('emergencia/create', emergencia_repository.emergencia_create),
    path('emergencia/<int:pk>/delete', emergencia_repository.emergencia_delete),
    path('atendimento', atendimento_repository.atendimentos_findall),
    path('atendimento/<int:pk>', atendimento_repository.atendimento_get),
    path('atendimento/<int:pk>/edit', atendimento_repository.atendimento_edit),
    path('atendimento/create', atendimento_repository.atendimento_create),
    path('atendimento/<int:pk>/delete', atendimento_repository.atendimento_delete),
    path('vacina', vacina_repository.vacinas_findall),
    path('vacina/<int:pk>', vacina_repository.vacina_get),
    path('vacina/<int:pk>/edit', vacina_repository.vacina_edit),
    path('vacina/create', vacina_repository.vacina_create),
    path('vacina/<int:pk>/delete', vacina_repository.vacina_delete),
    path('medicamento_administrado', medicamento_administrado_repository.medicamentos_administrados_findall),
    path('medicamento_administrado/<int:pk>', medicamento_administrado_repository.medicamento_administrado_get),
    path('medicamento_administrado/<int:pk>/edit', medicamento_administrado_repository.medicamento_administrado_edit),
    path('medicamento_administrado/create', medicamento_administrado_repository.medicamento_administrado_create),
    path('medicamento_administrado/<int:pk>/delete', medicamento_administrado_repository.medicamento_administrado_delete),
    path('medicamento', medicamento_repository.medicamentos_findall),
    path('medicamento/<int:pk>', medicamento_repository.medicamento_get),
    path('medicamento/<int:pk>/edit', medicamento_repository.medicamento_edit),
    path('medicamento/create', medicamento_repository.medicamento_create),
    path('medicamento/<int:pk>/delete', medicamento_repository.medicamento_delete),
    path('condicao_especial', condicao_especial_repository.condicoes_especiais_findall),
    path('condicao_especial/<int:pk>', condicao_especial_repository.condicao_especial_get),
    path('condicao_especial/<int:pk>/edit', condicao_especial_repository.condicao_especial_edit),
    path('condicao_especial/create', condicao_especial_repository.condicao_especial_create),
    path('condicao_especial/<int:pk>/delete', condicao_especial_repository.condicao_especial_delete),
    path('doenca', doenca_repository.doencas_findall),
    path('doenca/<int:pk>', doenca_repository.doenca_get),
    path('doenca/<int:pk>/edit', doenca_repository.doenca_edit),
    path('doenca/create', doenca_repository.doenca_create),
    path('doenca/<int:pk>/delete', doenca_repository.doenca_delete),
    path('receituario', receituario_repository.receitas_findall),
    path('receituario/<int:pk>', receituario_repository.receita_get),
    path('receituario/<int:pk>/edit', receituario_repository.receita_edit),
    path('receituario/create', receituario_repository.receita_create),
    path('receituario/<int:pk>/delete', receituario_repository.receita_delete),
]